version: "3.9"
services:
  client:
    build: ./client
    restart: on-failure
    ports:
      - "8080:80"
    volumes:
      - client:/client
  server:
    depends_on:
      - client
    build: ./server
    restart: on-failure
    ports:
      - "3000:3000"
    volumes:
      - server:/server
volumes:
  client: {}
  server: {}
