version: "3.9"
services:
  db:
    image: mysql:8.0.27
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - network1
  client:
    depends_on:
      - db
    build: ./client
    restart: on-failure
    env_file: ./.env
    ports:
      - "8080:80"
    volumes:
      - client:/client
    networks:
      - network1
      - network2
  server:
    depends_on:
      - db
      - client
    build: ./server
    restart: on-failure
    env_file: ./.env
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=$MYSQL_PASSWORD
      - DB_NAME=$MYSQL_DATABASE
      - DB_PORT=$MYSQL_PORT
    ports:
      - "3000:3000"
    volumes:
      - server:/server
    stdin_open: true
    tty: true
    networks:
      - network1
volumes:
  client: {}
  server: {}
  db: {}
networks:
  network1:
    internal: true
  network2:
    internal: false
