version: '3'

services:
  reverse-proxy:
    image: nginx:1.17.10
    container_name: reverse_proxy_zuko
    restart: always
    depends_on:
      - db
      - zuko-client
      - api-server
      - phpmyadmin
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "33006:80"
    env_file:
      - .env
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=$MYSQL_PASSWORD

  db:
    image: mysql:8.0.27
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
    ports:
      - "3306:3306"

  zuko-client:
    image: zuko-client
    container_name: zuko-client
    build:
      context: ./client
    restart: always
    env_file:
      - .env
    environment:
      - VUE_APP_BACKEND=$BACKEND
      - VUE_APP_IS_LOCAL_DEV=$IS_LOCAL_DEV
    depends_on:
      - api-server
    ports:
      - "8080:80"

  api-server:
    image: api-server
    container_name: api-server
    build:
      context: ./server
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DB_HOST=$DB_HOST
      - DB_USER=root
      - DB_PASSWORD=$MYSQL_PASSWORD
      - DB_NAME=$MYSQL_DATABASE
      - DB_PORT=$MYSQL_PORT
      - RE_SYNC=$RE_SYNC
    restart: always
    stdin_open: true
    tty: true

